language: python
os:
    - linux
python:
    - 3.6
sudo: false
install:
    - pip install -r requirements.txt
script:
    - mkdocs build
notifications:
  email:
    recipients:
    - banesullivan@gmail.com
    on_success: never
    on_failure: never

after_success:
    # Set configuration for repository and deploy documentation
    - REMOTE="https://${GH_TOKEN}@github.com/csmwteam/csmwteam.github.io"
    - git config --global user.name "${GH_NAME}"
    - git config --global user.email "${GH_EMAIL}"
    - git remote set-url origin ${REMOTE}
    - mkdocs gh-deploy --force -b master
    - mkdocs --version
